// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $webhook_sendEmailRoute from "./routes/webhook/sendEmailRoute.ts";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_nuvemshop from "./islands/AddToCartButton/nuvemshop.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $Authentication_ChangePassword from "./islands/Authentication/ChangePassword.tsx";
import * as $Authentication_Login from "./islands/Authentication/Login.tsx";
import * as $Authentication_RecoveryPassword from "./islands/Authentication/RecoveryPassword.tsx";
import * as $Authentication_Signup from "./islands/Authentication/Signup.tsx";
import * as $ButtonLogout from "./islands/ButtonLogout.tsx";
import * as $Cep from "./islands/Cep.tsx";
import * as $Cnpj from "./islands/Cnpj.tsx";
import * as $CorporationForm from "./islands/CorporationForm.tsx";
import * as $Cpf from "./islands/Cpf.tsx";
import * as $Form from "./islands/Form.tsx";
import * as $Header_Dreawer from "./islands/Header/Dreawer.tsx";
import * as $Header_MenuButton from "./islands/Header/MenuButton.tsx";
import * as $Input_Password from "./islands/Input/Password.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $PersonalForm from "./islands/PersonalForm.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $WarningConsent from "./islands/WarningConsent.tsx";
import * as $WishlistButton_vtex from "./islands/WishlistButton/vtex.tsx";
import * as $WishlistButton_wake from "./islands/WishlistButton/wake.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/webhook/sendEmailRoute.ts": $webhook_sendEmailRoute,
  },
  islands: {
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/nuvemshop.tsx": $AddToCartButton_nuvemshop,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/Authentication/ChangePassword.tsx":
      $Authentication_ChangePassword,
    "./islands/Authentication/Login.tsx": $Authentication_Login,
    "./islands/Authentication/RecoveryPassword.tsx":
      $Authentication_RecoveryPassword,
    "./islands/Authentication/Signup.tsx": $Authentication_Signup,
    "./islands/ButtonLogout.tsx": $ButtonLogout,
    "./islands/Cep.tsx": $Cep,
    "./islands/Cnpj.tsx": $Cnpj,
    "./islands/CorporationForm.tsx": $CorporationForm,
    "./islands/Cpf.tsx": $Cpf,
    "./islands/Form.tsx": $Form,
    "./islands/Header/Dreawer.tsx": $Header_Dreawer,
    "./islands/Header/MenuButton.tsx": $Header_MenuButton,
    "./islands/Input/Password.tsx": $Input_Password,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/PersonalForm.tsx": $PersonalForm,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/WarningConsent.tsx": $WarningConsent,
    "./islands/WishlistButton/vtex.tsx": $WishlistButton_vtex,
    "./islands/WishlistButton/wake.tsx": $WishlistButton_wake,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
